backend:
  name: git-gateway
  repo: chpmnrssll/agency
  squash_merges: true

media_folder: "/src/assets/images"
public_folder: "/src/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "settings"
    label: "Settings"
    files:
      - label: "Home page"
        name: "homePage"
        file: "/src/data/home.yml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Sub Header", name: "subHeader", widget: "string" }
          - { label: "CTA Button Text", name: "buttonText", widget: "string" }
      - label: "Footer"
        name: "footer"
        file: "/src/data/footer.yml"
        fields:
          - { label: "Text", name: "text", widget: "text" }
          - { label: "Show Netlify-CMS Link", name: "netlifyCMSLink", widget: "boolean", default: true, required: false }
