backend:
  name: git-gateway
  repo: chpmnrssll/agency
  squash_merges: true

media_folder: "/src/assets/images"
public_folder: "/src/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
